[package]
name = "dungeon"
version = "0.13.0"
authors = ["Patrick Clément-Bonhomme <patrick.cb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "~0.8.1"
legion="~0.3.0"
